# Generated by Django 5.2.7 on 2025-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_encryptedid_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonqid',
            name='birth_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonqid',
            name='hospitalization_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonqid',
            name='postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonqid',
            name='sex',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
