# Generated by Django 5.2.7 on 2025-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_anonqid_birth_date_anonqid_hospitalization_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255)),
                ('social_security_number', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('hospitalization_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('results', models.TextField()),
            ],
        ),
    ]
