# Generated by Django 5.2.7 on 2025-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_emr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
    ]
