# Generated by Django 5.2.7 on 2025-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChecksumAnon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
            ],
        ),
    ]
