# Generated by Django 5.2.7 on 2025-12-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_blocktag_checksumanon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktag',
            name='tag',
            field=models.BigIntegerField(),
        ),
    ]
